# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.0
  - 7.1
install: composer install --no-ansi --no-interaction --no-progress --prefer-dist
 
dist: trusty
# Commands to be run before your environment runs.
services:
 - mysql

# Commands you want to run that will verify your build.
script: vendor/bin/phpunit
env:
 - SYMFONY_VERSION="3.0.*" DB=mysql
# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 7.0
  
  fast_finish: true

