language: php

php:
  - 7.3.8
  - 7.2
before-install:
 - composer self-update
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
services:
  - mysql

install:
 - composer install
 - cp app/config/parameters.yml.dist app/config/parameters.yml
 - php bin/console doctrine:database:create --env=test
 - php bin/console doctrine:schema:create --env=test
 - php bin/console doctrine:fixtures:load -n --env=test
script: php phptest/testing.php